// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8mGCyO3gboO4tWwkGQfDSWWHT9JV5ics',
    appId: '1:619694478544:web:37dc421b12268c9948fad5',
    messagingSenderId: '619694478544',
    projectId: 'da-qlgarage',
    authDomain: 'da-qlgarage.firebaseapp.com',
    storageBucket: 'da-qlgarage.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASgNIg15xPvcJknjXwuOerBAZFzkUIHCs',
    appId: '1:619694478544:android:9989c77a5f30cd4548fad5',
    messagingSenderId: '619694478544',
    projectId: 'da-qlgarage',
    storageBucket: 'da-qlgarage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2qPj3fUs1adjFhpVIsv0lNPkVCRLYL58',
    appId: '1:619694478544:ios:30f81ada56f92bd348fad5',
    messagingSenderId: '619694478544',
    projectId: 'da-qlgarage',
    storageBucket: 'da-qlgarage.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );
}
